Repository I-GUIDE/iguide-ue-backend, pull requests merged in 2025-06, with the labels that each got.

#248 OpenSearch cleanup
  debug_scripts/opensearch_scripts/python_scripts/cross_validate_elements.py
Labels: enhancement

#249 [FEATURE]: Added a new display first name and last name parameters and updated PUT api/users/ API.
  backend_neo4j.js
  routes/elements.js
  routes/elements_utils.js
  routes/users.js
  tests/dev/users.test.js
  utils.js
Labels: todo-on-prod

#256 Automated tests working in an isolated environment
  routes/domain_utils.js
  server.js
  tests/README.md
  tests/secrets/.env.gpg
  tests/secrets/_.local.iguide.io/cert.pem
  tests/secrets/_.local.iguide.io/key.pem
  tests/secrets/decrypt.sh
  tests/secrets/localhost/cert.pem
  tests/secrets/localhost/key.pem
  tests/test-entrypoint.sh
Labels: documentation, enhancement, new backend function
